repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: no-commit-to-branch
        args: [--branch, main]
      - id: check-yaml
      - id: check-json
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
       - id: mypy
         args: [--ignore-missing-imports]